on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
    secrets:
      GOOGLE_CREDENTIALS:
        required: true
      SLACK_WEBHOOK:
        required: true
env:
  APP_NAME: ${{ inputs.appName }}
  
jobs:
  DEV:
    if: github.ref == 'refs/heads/dev'
    runs-on: Linux
    #runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build-dev

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: "Upload Source to Google Cloud"     
        id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'dist'
          destination: 'maika-ai-fe-dev'
          parent: false

      - name: Slack Notification Success
        if: ${{ success() }}
        uses: olli-ai/slack-notify-action@master
        env:
          SLACK_CHANNEL: alert-services
          SLACK_COLOR: ${{ job.status }} 
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: ':bell: FINISHED'
          SLACK_TITLE: 'Status Deploy Service Dev: ${{ env.APP_NAME }}'
          SLACK_USERNAME: devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
      - name: Slack Notification Failed
        if: ${{ failure() && steps.upload-folder.conclusion == 'failure' }}
        uses: olli-ai/slack-notify-action@master
        env:
          SLACK_CHANNEL: alert-services
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: ':x: ERROR'
          SLACK_TITLE: 'Status Deploy Service Dev: ${{ env.APP_NAME }}'
          SLACK_USERNAME: devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
  STAGING:
    if: github.ref == 'refs/heads/master'
    runs-on: Linux 
    #runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build-staging

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: "Upload Source to Google Cloud"     
        id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'dist'
          destination: 'maika-ai-fe-stg'
          parent: false

      - name: Slack Notification Success
        if: ${{ success() }}
        uses: olli-ai/slack-notify-action@master
        env:
          SLACK_CHANNEL: alert-services
          SLACK_COLOR: ${{ job.status }} 
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: ':bell: FINISHED'
          SLACK_TITLE: 'Status Deploy Service Staging: ${{ env.APP_NAME }}'
          SLACK_USERNAME: devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
      - name: Slack Notification Failed
        if: ${{ failure() && steps.upload-folder.conclusion == 'failure' }}
        uses: olli-ai/slack-notify-action@master
        env:
          SLACK_CHANNEL: alert-services
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: ':x: ERROR'
          SLACK_TITLE: 'Status Deploy Service Staging: ${{ env.APP_NAME }}'
          SLACK_USERNAME: devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
