name: Dev Build & Deploy

on:
  push:
    branches: ["dev"]
    paths-ignore:
      - 'values-dev.yaml'
    
jobs:
  verify:
    name: Verify file values changed
    runs-on: self-hosted
    outputs:
      opvf: ${{ steps.verify-changed-files.outputs.files_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
             values-dev.yaml
  build:
    needs: verify
    if: ${{needs.verify.outputs.opvf}} == 'false'
    uses: olli-ai/workflows-cicd/.github/workflows/build.yml@dev
    with:
      imageName: "maika-sh-adapter-service" 
      appName: "maika-sh-adapter-service" 
      approvers: HoaNM98,sonlm
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      TOKEN: ${{ secrets.TOKEN }}
  deploy:
    needs: verify
    if: ${{needs.verify.outputs.opvf}} == 'true'
    uses: olli-ai/workflows-cicd/.github/workflows/deploy.yml@dev
    with:
      imageName: "maika-sh-adapter-service" 
      appName: "maika-sh-adapter-service" 
      approvers: HoaNM98,sonlm
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      TOKEN: ${{ secrets.TOKEN }}
    
